[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SPUIS"
authors = [{name = "Martin van der Eijk", email = "martin.vandereijk@deltares.nl"}]
dynamic = ["version", "description"]
